# action.yml

name: 'diff'
description: 'return the list of files that has been changed within a commit'
outputs:
  diff-result: # id of output
    description: 'File name of the diff result'
runs:
  using: 'node12'
  main: 'dist/index.js'